In [2]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

sess.close()

0 Cost:  9890.555 
Prediction:
 [[54.484478]
 [70.104065]
 [66.80272 ]
 [73.2304  ]
 [53.893906]
 [40.363327]
 [53.72946 ]
 [38.32759 ]
 [66.8343  ]
 [62.931923]]
10 Cost:  9.081797 
Prediction:
 [[151.33318]
 [186.51863]
 [181.50148]
 [198.15283]
 [142.6762 ]
 [105.8307 ]
 [147.24518]
 [107.66379]
 [175.64293]
 [163.73122]]
20 Cost:  9.910689 
Prediction:
 [[151.98892]
 [187.29955]
 [182.2744 ]
 [198.99759]
 [143.26752]
 [106.27041]
 [147.88397]
 [108.1466 ]
 [176.37471]
 [164.41493]]
30 Cost:  9.891186 
Prediction:
 [[151.99554]
 [187.30016]
 [182.27855]
 [199.00505]
 [143.26373]
 [106.27129]
 [147.89598]
 [108.16472]
 [176.37715]
 [164.42305]]
40 Cost:  9.862994 
Prediction:
 [[151.99779 ]
 [187.2955  ]
 [182.27751 ]
 [199.00684 ]
 [143.25594 ]
 [106.26922 ]
 [147.90375 ]
 [108.179665]
 [176.37468 ]
 [164.42657 ]]
50 Cost:  9.834902 
Prediction:
 [[152.      ]
 [187.29082 ]
 [182.27644 ]
 [199.00859 ]
 [143.24814 ]
 [106.267105]
 [147.91145 ]
 [108.194534]
 [176.37218 ]
 [164.43005 

620 Cost:  8.447556 
Prediction:
 [[152.12433 ]
 [187.03902 ]
 [182.22272 ]
 [199.1013  ]
 [142.83153 ]
 [106.146484]
 [148.31853 ]
 [108.98024 ]
 [176.22862 ]
 [164.59564 ]]
630 Cost:  8.426622 
Prediction:
 [[152.12646]
 [187.03485]
 [182.2219 ]
 [199.10281]
 [142.82469]
 [106.14437]
 [148.32513]
 [108.99298]
 [176.2261 ]
 [164.59802]]
640 Cost:  8.4057455 
Prediction:
 [[152.1286  ]
 [187.03067 ]
 [182.22102 ]
 [199.1043  ]
 [142.81786 ]
 [106.14225 ]
 [148.3317  ]
 [109.005684]
 [176.22359 ]
 [164.60039 ]]
650 Cost:  8.385038 
Prediction:
 [[152.13075]
 [187.02654]
 [182.22021]
 [199.1058 ]
 [142.81105]
 [106.14014]
 [148.33827]
 [109.01836]
 [176.22107]
 [164.60275]]
660 Cost:  8.364401 
Prediction:
 [[152.13289 ]
 [187.02238 ]
 [182.2194  ]
 [199.10728 ]
 [142.80426 ]
 [106.13802 ]
 [148.3448  ]
 [109.031006]
 [176.21857 ]
 [164.60509 ]]
670 Cost:  8.343895 
Prediction:
 [[152.13503]
 [187.01826]
 [182.2186 ]
 [199.10878]
 [142.79749]
 [106.13592]
 [148.35133]
 [109.04362]
 [176.

1250 Cost:  7.314702 
Prediction:
 [[152.25548]
 [186.79247]
 [182.17682]
 [199.1886 ]
 [142.42969]
 [106.01482]
 [148.70154]
 [109.72025]
 [176.07219]
 [164.71812]]
1260 Cost:  7.299466 
Prediction:
 [[152.25749 ]
 [186.7888  ]
 [182.1762  ]
 [199.18987 ]
 [142.42377 ]
 [106.012764]
 [148.70712 ]
 [109.73103 ]
 [176.06978 ]
 [164.71965 ]]
1270 Cost:  7.2842956 
Prediction:
 [[152.25949]
 [186.78516]
 [182.17554]
 [199.19113]
 [142.41785]
 [106.01072]
 [148.71266]
 [109.74178]
 [176.06732]
 [164.72116]]
1280 Cost:  7.2692323 
Prediction:
 [[152.2615  ]
 [186.78151 ]
 [182.17493 ]
 [199.1924  ]
 [142.41196 ]
 [106.00867 ]
 [148.71822 ]
 [109.752495]
 [176.0649  ]
 [164.72269 ]]
1290 Cost:  7.2542295 
Prediction:
 [[152.26352 ]
 [186.77788 ]
 [182.17432 ]
 [199.19366 ]
 [142.4061  ]
 [106.006615]
 [148.72375 ]
 [109.76319 ]
 [176.06247 ]
 [164.72418 ]]
1300 Cost:  7.239274 
Prediction:
 [[152.26552]
 [186.77425]
 [182.17368]
 [199.1949 ]
 [142.4002 ]
 [106.00457]
 [148.72926]
 [109.77386

1830 Cost:  6.5469084 
Prediction:
 [[152.36838]
 [186.59245]
 [182.14424]
 [199.25703]
 [142.10788]
 [105.89864]
 [149.00157]
 [110.30047]
 [175.93439]
 [164.79019]]
1840 Cost:  6.5355363 
Prediction:
 [[152.37024]
 [186.5892 ]
 [182.14374]
 [199.25812]
 [142.10269]
 [105.8967 ]
 [149.00635]
 [110.30971]
 [175.93207]
 [164.79117]]
1850 Cost:  6.524247 
Prediction:
 [[152.37212]
 [186.586  ]
 [182.14325]
 [199.25922]
 [142.09753]
 [105.89475]
 [149.01114]
 [110.31893]
 [175.92978]
 [164.79213]]
1860 Cost:  6.5129676 
Prediction:
 [[152.37398 ]
 [186.58275 ]
 [182.14275 ]
 [199.26028 ]
 [142.09236 ]
 [105.892815]
 [149.01585 ]
 [110.32813 ]
 [175.92746 ]
 [164.79308 ]]
1870 Cost:  6.5018167 
Prediction:
 [[152.37584 ]
 [186.57954 ]
 [182.14229 ]
 [199.26138 ]
 [142.08723 ]
 [105.89088 ]
 [149.02061 ]
 [110.337296]
 [175.92517 ]
 [164.79402 ]]
1880 Cost:  6.490657 
Prediction:
 [[152.37769]
 [186.57632]
 [182.14178]
 [199.26245]
 [142.08209]
 [105.88894]
 [149.02533]
 [110.34644]
 [175.9